### ISSUE TITLE
[DMF] edci_credential.xsd is not valid (e.g. in Saxon 9.9)

### ISSUE THREAD

**Issue by SebastianSklarss** [european-commission-empl/European-Learning-Model#31]
**init AG in charge of the German XML metadata profile [www.xhochschule.de](url
!http://www.xheie.eu/) currently reusing and national profiling EDCI**

**Specify the *nature* of your comment**
* a question about the data model or a specific content item
* a suggested change or adjustment 

**Free text comment**
EDCI Version 0.10.0 can not be validated using Saxon 9.9. 
The reason seems to be incorrect syntax (not allowed elements).
It looks like it was valid im former versions and now became invalid due to changes that were not made everywhere where necessary.

![image](https://user-images.githubusercontent.com/70315945/94783618-3c503300-03cd-11eb-957f-f5adccdb9270.png)

**Comment by anthonycamilleri** [comment]
Being addressed for 1.0

**Comment by XHochschuleDE** [comment]
Unfortunately the errors have not been fixed in 1.0.

As long as Saxon-EE cannot parse the schema without errors and warnings the German XML metadata profile cannot import the schema.

**Comment by anthonycamilleri** [comment]
Reopening to address issue.

**Comment by anthonycamilleri** [comment]
Closed, as XSD deprecated.
