### ISSUE TITLE
[DMF] QR Code representation? 

### ISSUE THREAD

**Issue by vitorpamplona** [european-commission-empl/European-Learning-Model#41]
**Describe the organization you represent**
I am the CTO for [PathCheck](http://pathcheck.org) and working on an open-source extension of the W3C model of Verifiable Credentials (similar to what was done here) to [URI-based schemas for QR codes](https://github.com/Path-Check/paper-cred). We currently focus on COVID/health-related information (Vaccine Passes, Test Results, Immunization Records, etc), some types of ID cards, contracts, and intellectual property-based credentials but I would love to check if the same model could be applied to Educational payloads as well. 

**Specify the *nature* of your comment**
I noticed the preference for the XML/XSD payload and I am wondering if there is any support to convert those XMLs to signed QR Codes and/or if the group has thought about it. The idea here is to provide an equitable, hopefully unifying, way to receive and share Verifiable Credentials that can also include machine-readable paper-based representations. Those QR Codes can be used to add a signature to existing paper-based certificates, thus allowing distribution and verification completely non-digital (beyond just offline). 

**Free text comment**
I am not sure if this feedback form is the best way to discuss this. If not, you can also find me at vitor.pamplona@pathcheck.org. I would love to discuss the current thinking about QRs on a Zoom call.

**Comment by anthonycamilleri** [comment]
This is now addressed in EDC 1.7. Users may create a sharelink to a credential from within the EDC Viewer application. The link uses content negotiation to serve up a VP of the credential or a view of the credential in a web link.
