### ISSUE TITLE
Kind-of-Diploma for German Upper Secondary School Diploma

### ISSUE THREAD

**Issue by GBacharach** [european-commission-empl/European-Learning-Model#47]
For upper secondary school diplomas (in German “Hochschulzugangsberechtigungen”, short HZB) Germany needs the diploma learning-opportunity’s kind-of-diploma to verify whether this certificate qualifies the applicant to study the study program he applies for. E.g.

Unfortunately EQF-levels are not enough for our purposes. Especially for diplomas within EQF 4 we need more differentiations e.g.

    “Allgemeine Hochschulreife” The owner has the right to study (in Germany) whatever and wherever he likes
    “Fachhochschulreife” The owner has the right only to study at universities of applied sciences (colleges)
    “Fachgebundene Hochschulreife” The owner has the right only to study special study programs
    …

It is to be clarified, how the different German upper secondary school education certificates can be mapped in the ELMO data structure. We do not have precisely this differentiation in EQF level 4, even at the German national level (see https://www.cedefop.europa.eu/files/germany_-_european_inventory_on_nqf_2018.pdf page 13):

    Upper secondary general education school leaving certificate (Allgemeine Hochschulreife (AHR))
    Qualification entitling holder to study particular subjects at a higher education institution (Fachgebundene Hochschulreife (FgbHR))
    Qualification entitling holder to study at a university of applied sciences (Fachhochschulreife (FHR))
    Dual VET (three-year and three-and-a-half-year training courses)
    Full-time vocational school (regulated under Länder law) (Berufsfachschule)
    Full vocational qualification (full-time vocational school) (Berufsfachschule)

Germany users need an extension of the ELM standard here so that we can automatically assign the digital HZBs. Or is there another way to get the information out of ELM structure for German users?

By the way: ELMO have the same problem.

**Comment by anthonycamilleri** [comment]
In ELMv3 the achievement-type property can be used to describe this functionality.
