### ISSUE TITLE
Additional three grading schemes for German Upper Secondary School Diploma

### ISSUE THREAD

**Issue by GBacharach** [european-commission-empl/European-Learning-Model#48]
The German SfH would like to use EMREX for national and international access to digitized upper secondary school diplomas.

Trying to use the current ELMO version for German upper secondary school diplomas (“HZB – Hochschulzugangsberechtigung”) the problem showed up, that the following data necessary for a German “HZB” do not exist in this version of ELMO schema:

Certificate-specific characteristics (to be added maybe to the “Learning Opportunity” of ELMO-structure)

    Additionally, three grading schemes have to be defined for German HZBs to describe an average grade and a score:
    -- Average grade,
    -- grade in points 300-900
    -- grade in points 280-840

Remarks to these certificate-specific characteristics:
Germany needs at total three grading schemes to describe the grade of a German HZB: The grade can be given either as average grade (1.0, 1.1, …, 4.0), grade in points 300-900 or grade in points 280-840. It is possible, that for special HZBs there is no grade in points but only an average grade given, so it is not always possible to calculate the average grade (out of one grade in points).

n the ELMO workshop in Göttingen there were questions whether it is really necessary for Germany to distinguish between 3 different evaluation schemes, or whether only one occurs per certificate and the others can then be calculated uniquely from this by an algorithm?

So the question that had to be clarified is whether an identification of which type is the evaluation scheme is sufficient, or whether different evaluation schemes are also needed at the same time.

The department of SfH, which is responsible for such questions, have examined this question in detail and have come to the following conclusion:

_" ... as a result, however, the German upper secondary school diploma (Deutsch Hochschulzugangsberechtigung, HZB for short) needs the different schemes.

Currently, there are always three elements per certificate that are relevant for the calculation of the procedure score:

    average score (Deutsch Durchschnittsnote, DN for short),
    concrete score of the DN and
    maximum achievable total score.

Example: DN = 1.5; corresponding score = 733 (range between 750 - 733 points); with a total score of max. 900 points.

Due to the large number of different HZBs within different years, these three certificate elements - with regard to the total score - occur in three variants:

    Variant with sample data
    average grade, [ = 1,5 ]
    concrete score of the DN [ = 733 points; with a range of 750 - 733 points] and
    total score 300-900 points [ = max. 900 points ].

    Variant with sample data
    average score, [ = 1.5 ]
    concrete score of DN [ = 684 points; with a range of 700 - 684 points] and
    total score 280-840 points [ = max. 840 points ]

    Variant with sample data
    Average score, [ = 1.5 ]
    corresponding score of DN [if not shown, an average is calculated based on the total score of 900 points to calculate the procedure score; here: 742 points ]and
    Total score other (i.e. a total score that differs from the first two variants or is not explicitly shown).

Thus, currently three elements of a variant are always shown per certificate.

The algorithm mentioned in the ELMO workshop is likely to fail already due to the fact that for certificates with a 1.0 there is an overlap of the scores from both total score systems (900 and 840). This means a clear assignment to the 900 or 840 system is not possible for applicants with a 1.0 from a concrete score of 823 points."

**Comment by anthonycamilleri** [comment]
In ELMv3 we have assessments as a separate concept. One achievement can be made up of multiple assessments each with their own grading scheme.
