### ISSUE TITLE
Address of issuer for German Upper Secondary School Diploma

### ISSUE THREAD

**Issue by GBacharach** [european-commission-empl/European-Learning-Model#51]
The German SfH would like to use EMREX for national and international access to digitized upper secondary school diplomas.

Trying to use the current ELMO version for German upper secondary school diplomas (“HZB – Hochschulzugangsberechtigung”) the problem showed up, that the following data necessary for a German “HZB” do not exist in this version of ELMO schema:

Institution-specific characteristic (to be added to the “Issuer” of ELMO-structure) - Address

Remarks to the additional institution-specific characteristic:
SfH needs the address of the diploma issuer to get a unique identification of the issuer (school).

**Comment by anthonycamilleri** [comment]
Possible in ELM v3
