### ISSUE TITLE
[EDC Constraints shacl] update - remove fields that may cause loops

### ISSUE THREAD

**Issue by rdolcetr** [european-commission-empl/European-Learning-Model#56]
Update EDC-constraints.ttl file; Some fields may cause a loop if informed. This fields should be removed from the DM:

* AwardingOpportunity - elm:learningAchievementSpecification

* AwardingProcess - elm:awards

* LearningAchievement - elm:isPartOf
* LearningActivity - elm:isPartOf
* LearningAssessment - elm:isPartOf
* LearningEntitlement - elm:isPartOf
* LearningOpportunity - elm:isPartOf
* LearningOpportunity - elm:isPartOf

* Organisation - org:subOrganizationOf

Update JSON-LD file if necessary

**Comment by NatasaSofou** [comment]
It was agreed  to include inverse properties in the ontology.  Shall  we remove them from edc-ap shacl or from the ontology as well?

**Comment by jan-forster-cognizone** [comment]
Many parts of the model can result in loops (not only these direct ones, but also loops of several steps). General practice is to solve this on an application level when flattening the graph for specific purposes.

**Comment by Esayos** [comment]
Hi everyone, 

As the ontology is not longer being used at the AP validation process, is this now possible?
We do check for loops (including several steps loops) at application level before creating the JSON files but constraint **edc:AwardingProcess-elm_awards mincount 1** is forcing us to create a loop (Claim->AwardedBy->Awards->Claim) that we would rather avoid. If removing bidirectional relations is not possible, could alternatively remove this constraint?

**Comment by NatasaSofou** [comment]
Proposed solution:  Remove inverse properties from EDC-ap, but keep them in the ontology.

**Comment by jan-forster-cognizone** [comment]
Hi, was this cleared with @anthonycamilleri? In the past, we agreed to keep the inverses. We could remove them as Natasa suggests, but it would not be an advisable approach from the modelling point of view.

**Comment by rdolcetr** [comment]
Closing this issue. Instead of removing the fields, we'll be making them optional. New ticket opened for this: #70
