### ISSUE TITLE
[JSON-LD Context & EDC Constraints shacl] update - rename hasSubOrganization

### ISSUE THREAD

**Issue by rdolcetr** [european-commission-empl/European-Learning-Model#57]
Change the Z in the field Organisation org:hasSubOrganization in both EDC-constraints.ttl and edc-ap-context.jsonld

**Comment by NatasaSofou** [comment]
This property  URI is reuse from w3c Organization ontology, it is american english, so we need to use the URI as it is.

**Comment by rdolcetr** [comment]
Closing the issue for the reasons mentioned by Natasa
