### ISSUE TITLE
Add AccreditationStatus to Accreditation Class

### ISSUE THREAD

**Issue by anthonycamilleri** [european-commission-empl/European-Learning-Model#63]
In addition to 'publication status', accreditation status should be added to the accreditation class. It should be 0...1 and use terms from https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://data.europa.eu/snb/status/25831c2

**Comment by NatasaSofou** [comment]
I think that  elm:Accreditation:: elm:status is the property  you are referring to because in the controlled vocabulary restriction, this property  has values from <https://publications.europa.eu/resource/authority/snb/status/25831c2>;
