### ISSUE TITLE
[EDC-Constraints SHACL] remove **uniqueLang** in multilang fields

### ISSUE THREAD

**Issue by rdolcetr** [european-commission-empl/European-Learning-Model#78]
The credential's multilang fields defined with a sh:datatype **rdf:langString;** are limited to have only one entry fro each language.
It seems that this restriction is performed by using the uniqueLang rule on them. 

To make the datamodel more flexible could we remove this restriction from our shacle file?

**Comment by IldikoMazar** [comment]
I support Robert's request, please remove this restriction from the SHACL file, thank you.
