### ISSUE TITLE
EDC ELMv3 xsd

### ISSUE THREAD

**Issue by miguelfn** [european-commission-empl/European-Learning-Model#93]
A few weeks ago, the xsd files loq.xsd and ams.xsd corresponding to ELMv3 were released (master branch, and tag 3.0). 

Is it planned to release xsd files for the generation of European Digital Credentials (edc)?

**Comment by anthonycamilleri** [comment]
@miguelfn with version 3.0 EDC moves to a JSON-LD format, with no serialisation available in XML/XSD so as to have full compatibility with the Verifiable Credentials data model. While the EDC infrastructure will still accept ELM v2 credentials in XML, moving forward the credentials profile will be JSON only.
